import React from "react";
import {
  AbandonedCartFilledMajor,
  AbandonedCartMajor,
  AccessibilityMajor,
  ActivitiesMajor,
  AddCodeMajor,
  AddImageMajor,
  AddMajor,
  AddNoteMajor,
  AddProductMajor,
  AdjustMinor,
  AffiliateMajor,
  AlertMinor,
  AnalyticsBarHorizontalMinor,
  AnalyticsBarStackedMinor,
  AnalyticsCohortMinor,
  AnalyticsDonutMinor,
  AnalyticsFilledMinor,
  AnalyticsFunnelMinor,
  AnalyticsLineMinor,
  AnalyticsMajor,
  AnalyticsMinor,
  AnalyticsTableMinor,
  AnyClickModelMinor,
  AppExtensionMinor,
  AppsFilledMajor,
  AppsMajor,
  AppsMinor,
  ArchiveMajor,
  ArchiveMinor,
  ArrowDownMinor,
  ArrowLeftMinor,
  ArrowRightMinor,
  ArrowUpMinor,
  AttachmentFilledMajor,
  AttachmentMajor,
  AutomationFilledMajor,
  AutomationMajor,
  BackspaceMajor,
  BalanceFilledMajor,
  BalanceMajor,
  BankFilledMajor,
  BankMajor,
  BarcodeMajor,
  BehaviorFilledMajor,
  BehaviorMajor,
  BehaviorMinor,
  BillingStatementDollarFilledMajor,
  BillingStatementDollarMajor,
  BillingStatementEuroFilledMajor,
  BillingStatementEuroMajor,
  BillingStatementPoundFilledMajor,
  BillingStatementPoundMajor,
  BillingStatementRupeeFilledMajor,
  BillingStatementRupeeMajor,
  BillingStatementYenFilledMajor,
  BillingStatementYenMajor,
  BlockMinor,
  BlockquoteMajor,
  BlogMajor,
  BoldMajor,
  BoldMinor,
  BugMajor,
  ButtonCornerPillMajor,
  ButtonCornerRoundedMajor,
  ButtonCornerSquareMajor,
  ButtonMinor,
  BuyButtonButtonLayoutMajor,
  BuyButtonHorizontalLayoutMajor,
  BuyButtonMajor,
  BuyButtonVerticalLayoutMajor,
  CalendarMajor,
  CalendarMinor,
  CalendarTickMajor,
  CalendarTimeMinor,
  CameraMajor,
  CancelMajor,
  CancelMinor,
  CancelSmallMinor,
  CapitalFilledMajor,
  CapitalMajor,
  CapturePaymentMinor,
  CardReaderChipMajor,
  CardReaderMajor,
  CardReaderTapMajor,
  CaretDownMinor,
  CaretUpMinor,
  CartDownFilledMajor,
  CartDownMajor,
  CartFilledMajor,
  CartMajor,
  CartUpMajor,
  CashDollarFilledMajor,
  CashDollarMajor,
  CashDollarMinor,
  CashEuroMajor,
  CashPoundMajor,
  CashRupeeMajor,
  CashYenMajor,
  CategoriesMajor,
  ChannelsMajor,
  ChatMajor,
  ChecklistAlternateMajor,
  ChecklistMajor,
  CheckoutMajor,
  ChevronDownMinor,
  ChevronLeftMinor,
  ChevronRightMinor,
  ChevronUpMinor,
  CircleAlertMajor,
  CircleCancelMajor,
  CircleCancelMinor,
  CircleChevronDownMinor,
  CircleChevronLeftMinor,
  CircleChevronRightMinor,
  CircleChevronUpMinor,
  CircleDisableMinor,
  CircleDisabledMajor,
  CircleDotsMajor,
  CircleDownMajor,
  CircleInformationMajor,
  CircleLeftMajor,
  CircleMinusMajor,
  CircleMinusMinor,
  CircleMinusOutlineMinor,
  CirclePlusMajor,
  CirclePlusMinor,
  CirclePlusOutlineMinor,
  CircleRightMajor,
  CircleTickMajor,
  CircleTickMinor,
  CircleTickOutlineMinor,
  CircleUpMajor,
  ClipboardMinor,
  ClockMajor,
  ClockMinor,
  CodeMajor,
  CodeMinor,
  CollectionReferenceMinor,
  CollectionsFilledMajor,
  CollectionsMajor,
  ColorNoneMinor,
  ColorsMajor,
  Column1Major,
  ColumnWithTextMajor,
  Columns2Major,
  Columns3Major,
  Columns3Minor,
  ComposeMajor,
  ConfettiMajor,
  ConnectMinor,
  ContentFilledMinor,
  ContentMinor,
  ConversationMinor,
  CreditCardCancelMajor,
  CreditCardMajor,
  CreditCardPercentMajor,
  CreditCardSecureMajor,
  CurrencyConvertMinor,
  CustomerMinusMajor,
  CustomerPlusMajor,
  CustomersFilledMinor,
  CustomersMajor,
  CustomersMinor,
  DataDrivenModelMinor,
  DataVisualizationMajor,
  DecimalMinor,
  DeleteMajor,
  DeleteMinor,
  DesktopMajor,
  DetailedPopUpMajor,
  DiamondAlertMajor,
  DiamondAlertMinor,
  DigitalMediaReceiverMajor,
  DiscountAutomaticMajor,
  DiscountCodeMajor,
  DiscountsFilledMinor,
  DiscountsMajor,
  DiscountsMinor,
  DisputeMinor,
  DnsSettingsMajor,
  DockFloatingMajor,
  DockSideMajor,
  DomainNewMajor,
  DomainRedirectMinor,
  DomainsFilledMajor,
  DomainsMajor,
  DraftOrdersFilledMajor,
  DraftOrdersMajor,
  DragDropMajor,
  DragHandleMinor,
  DropdownMinor,
  DuplicateMinor,
  DynamicSourceMajor,
  DynamicSourceMinor,
  EditMajor,
  EditMinor,
  EmailMajor,
  EmailNewsletterMajor,
  EmbedMinor,
  EnableSelectionMinor,
  EnterMajor,
  EnvelopeMajor,
  ExchangeMajor,
  ExistingInventoryMajor,
  ExitMajor,
  ExploreImagesMajor,
  ExportMinor,
  ExtendMajor,
  ExtendMinor,
  ExternalMinor,
  ExternalSmallMinor,
  EyeDropperMinor,
  FacebookMinor,
  FaviconMajor,
  FavoriteMajor,
  FeaturedCollectionMajor,
  FeaturedContentMajor,
  FileFilledMinor,
  FileMinor,
  FilterMajor,
  FilterMinor,
  FinancesMajor,
  FinancesMinor,
  FirstClickModelMinor,
  FirstOrderMajor,
  FirstVisitMajor,
  FlagMajor,
  FlipCameraMajor,
  FolderDownMajor,
  FolderMajor,
  FolderMinusMajor,
  FolderPlusMajor,
  FolderUpMajor,
  FollowUpEmailMajor,
  FoodMajor,
  FooterMajor,
  FormsMajor,
  FraudProtectMajor,
  FraudProtectMinor,
  FraudProtectPendingMajor,
  FraudProtectPendingMinor,
  FraudProtectUnprotectedMajor,
  FraudProtectUnprotectedMinor,
  FulfillmentFulfilledMajor,
  FulfillmentOnHoldMajor,
  GamesConsoleMajor,
  GaugeMajor,
  GaugeMinor,
  GiftCardFilledMinor,
  GiftCardMajor,
  GiftCardMinor,
  GlobeMajor,
  GlobeMinor,
  GrammarMajor,
  HashtagMajor,
  HashtagMinor,
  HeaderMajor,
  HeartMajor,
  HideKeyboardMajor,
  HideMinor,
  HintMajor,
  HomeFilledMinor,
  HomeMajor,
  HomeMinor,
  HorizontalDotsMinor,
  IconsFilledMajor,
  IconsMajor,
  IdentityCardFilledMajor,
  IdentityCardMajor,
  IllustrationMajor,
  ImageAltMajor,
  ImageAltMinor,
  ImageMajor,
  ImageWithTextMajor,
  ImageWithTextOverlayMajor,
  ImagesMajor,
  ImportMinor,
  ImportStoreMajor,
  InactiveLocationMajor,
  InactiveLocationMinor,
  IncomingMajor,
  IndentMajor,
  IndentMinor,
  InfoMinor,
  InsertDynamicSourceMajor,
  InsertDynamicSourceMinor,
  InstagramMinor,
  InstallMinor,
  InventoryFilledMajor,
  InventoryMajor,
  InviteMinor,
  IqMajor,
  ItalicMajor,
  ItalicMinor,
  JobsFilledMajor,
  JobsMajor,
  KeyMajor,
  KeyboardMajor,
  KeyboardMinor,
  LabelPrinterMajor,
  LandingPageMajor,
  LanguageFilledMinor,
  LanguageMinor,
  LastClickModelMinor,
  LastNonDirectClickModelMinor,
  LegalFilledMajor,
  LegalMajor,
  LinearModelMinor,
  LinkMinor,
  ListFilledMajor,
  ListMajor,
  ListMinor,
  LiveViewFilledMajor,
  LiveViewMajor,
  LocationFilledMajor,
  LocationMajor,
  LocationsMinor,
  LockFilledMajor,
  LockMajor,
  LockMinor,
  LogOutMinor,
  LogoBlockMajor,
  MagicMajor,
  MagicMinor,
  ManagedStoreMajor,
  MarkFulfilledMinor,
  MarkPaidMinor,
  MarketingFilledMinor,
  MarketingMajor,
  MarketingMinor,
  MarketsFilledMajor,
  MarketsMajor,
  MaximizeMajor,
  MaximizeMinor,
  MeasurementMinor,
  MentionMajor,
  MergeMinor,
  MetafieldsFilledMinor,
  MetafieldsMajor,
  MetafieldsMinor,
  MetaobjectMinor,
  MetaobjectReferenceMinor,
  MicrophoneMajor,
  MinimizeMajor,
  MinimizeMinor,
  MinusMajor,
  MinusMinor,
  MobileAcceptMajor,
  MobileBackArrowMajor,
  MobileCancelMajor,
  MobileChevronMajor,
  MobileHamburgerMajor,
  MobileHorizontalDotsMajor,
  MobileMajor,
  MobilePlusMajor,
  MobileVerticalDotsMajor,
  MonerisMajor,
  MoneyFilledMinor,
  MoneyMinor,
  NatureMajor,
  NavigationMajor,
  NoteMajor,
  NoteMinor,
  NotificationFilledMajor,
  NotificationMajor,
  OnlineStoreMajor,
  OnlineStoreMinor,
  OrderStatusMinor,
  OrderedListMajor,
  OrderedListMinor,
  OrdersFilledMinor,
  OrdersMajor,
  OrdersMinor,
  OrganizationMajor,
  OutdentMajor,
  OutdentMinor,
  OutgoingMajor,
  PackageFilledMajor,
  PackageMajor,
  PageDownMajor,
  PageMajor,
  PageMinusMajor,
  PagePlusMajor,
  PageReferenceMinor,
  PageUpMajor,
  PaginationEndMinor,
  PaginationStartMinor,
  PaintBrushMajor,
  PaperCheckMajor,
  PaperCheckMinor,
  PasskeyFilledMinor,
  PasskeyMajor,
  PasskeyMinor,
  PauseCircleMajor,
  PauseMajor,
  PauseMinor,
  PaymentsFilledMajor,
  PaymentsMajor,
  PayoutsBlockedMinor,
  PersonalizedTextMajor,
  PhoneInMajor,
  PhoneMajor,
  PhoneOutMajor,
  PinMajor,
  PinMinor,
  PinUnfilledMajor,
  PinUnfilledMinor,
  PintrestMinor,
  PlanFilledMinor,
  PlanMajor,
  PlanMinor,
  PlayCircleMajor,
  PlayMajor,
  PlayMinor,
  PlusMinor,
  PointOfSaleMajor,
  PopularMajor,
  PositionBasedModelMinor,
  PriceLookupMinor,
  PrintMajor,
  PrintMinor,
  ProductCostMajor,
  ProductReferenceMinor,
  ProductReturnsMinor,
  ProductsFilledMinor,
  ProductsMajor,
  ProductsMinor,
  ProfileMajor,
  ProfileMinor,
  PromoteFilledMinor,
  PromoteMinor,
  QuestionMarkInverseMajor,
  QuestionMarkInverseMinor,
  QuestionMarkMajor,
  QuestionMarkMinor,
  QuickSaleMajor,
  ReadTimeMinor,
  ReceiptMajor,
  RecentSearchesMajor,
  RedoMajor,
  ReferralCodeMajor,
  ReferralMajor,
  RefreshMajor,
  RefreshMinor,
  RefundMajor,
  RefundMinor,
  RemoveProductMajor,
  RepeatOrderMajor,
  ReplaceMajor,
  ReplayMinor,
  ReportFilledMinor,
  ReportMinor,
  ReportsMajor,
  ResetMinor,
  ResourcesMajor,
  ReturnMinor,
  ReturnsMajor,
  RichTextMinor,
  RiskMajor,
  RiskMinor,
  Rows2Major,
  SandboxMajor,
  SaveMinor,
  SearchMajor,
  SearchMinor,
  SectionMajor,
  SecureMajor,
  SelectMinor,
  SendMajor,
  SettingsFilledMinor,
  SettingsMajor,
  SettingsMinor,
  ShareIosMinor,
  ShareMinor,
  ShipmentFilledMajor,
  ShipmentMajor,
  ShopcodesMajor,
  SidebarLeftMajor,
  SidebarRightMajor,
  SidekickMajor,
  SimplifyMajor,
  SimplifyMinor,
  SlideshowMajor,
  SmileyHappyMajor,
  SmileyJoyMajor,
  SmileyNeutralMajor,
  SmileySadMajor,
  SnapchatMinor,
  SocialAdMajor,
  SocialPostMajor,
  SoftPackMajor,
  SortAscendingMajor,
  SortDescendingMajor,
  SortMinor,
  SoundMajor,
  StarFilledMinor,
  StarOutlineMinor,
  StatusActiveMajor,
  StopMajor,
  StoreDetailsFilledMinor,
  StoreDetailsMinor,
  StoreFilledMinor,
  StoreMajor,
  StoreMinor,
  StoreStatusMajor,
  TabletMajor,
  TapChipMajor,
  TaxFilledMajor,
  TaxMajor,
  TeamMajor,
  TemplateMajor,
  TemplateMinor,
  TextAlignmentCenterMajor,
  TextAlignmentLeftMajor,
  TextAlignmentRightMajor,
  TextBlockMajor,
  TextColorMajor,
  TextColorMinor,
  TextMajor,
  ThemeEditMajor,
  ThemeStoreMajor,
  ThemesMajor,
  ThumbsDownMajor,
  ThumbsDownMinor,
  ThumbsUpMajor,
  ThumbsUpMinor,
  TickMinor,
  TickSmallMinor,
  TiktokMinor,
  TimeDecayModelMinor,
  TimelineAttachmentMajor,
  TipsMajor,
  TitleMinor,
  ToggleMinor,
  ToolsMajor,
  TransactionFeeDollarMajor,
  TransactionFeeEuroMajor,
  TransactionFeePoundMajor,
  TransactionFeeRupeeMajor,
  TransactionFeeYenMajor,
  TransactionMajor,
  TransferFilledMajor,
  TransferInMajor,
  TransferMajor,
  TransferOutMajor,
  TransferWithinShopifyMajor,
  TranslateMajor,
  TransportMajor,
  TroubleshootMajor,
  TumblrMinor,
  TwitchMinor,
  TwitterMinor,
  TypeMajor,
  TypeMinor,
  UnderlineMajor,
  UnderlineMinor,
  UndoMajor,
  UnfulfilledMajor,
  UnknownDeviceMajor,
  UpdateInventoryMajor,
  UploadMajor,
  VariantMajor,
  ViewMajor,
  ViewMinor,
  ViewportNarrowMajor,
  ViewportShortMajor,
  ViewportTallMajor,
  ViewportWideMajor,
  VimeoMinor,
  VocabularyMajor,
  VolumeMinor,
  WandMajor,
  WandMinor,
  WearableMajor,
  WeightMinor,
  WholesaleMajor,
  WifiMajor,
  YoutubeMinor,
} from "@shopify/polaris-icons";
import { Icon, InlineGrid, InlineStack, Text } from "@shopify/polaris";

export default function PolarisIcons() {
  const icons = [
    { icon: AbandonedCartFilledMajor, name: "AbandonedCartFilledMajor" },
    { icon: AbandonedCartMajor, name: "AbandonedCartMajor" },
    { icon: AccessibilityMajor, name: "AccessibilityMajor" },
    { icon: ActivitiesMajor, name: "ActivitiesMajor" },
    { icon: AddCodeMajor, name: "AddCodeMajor" },
    { icon: AddImageMajor, name: "AddImageMajor" },
    { icon: AddMajor, name: "AddMajor" },
    { icon: AddNoteMajor, name: "AddNoteMajor" },
    { icon: AddProductMajor, name: "AddProductMajor" },
    { icon: AdjustMinor, name: "AdjustMinor" },
    { icon: AffiliateMajor, name: "AffiliateMajor" },
    { icon: AlertMinor, name: "AlertMinor" },
    { icon: AnalyticsBarHorizontalMinor, name: "AnalyticsBarHorizontalMinor" },
    { icon: AnalyticsBarStackedMinor, name: "AnalyticsBarStackedMinor" },
    { icon: AnalyticsCohortMinor, name: "AnalyticsCohortMinor" },
    { icon: AnalyticsDonutMinor, name: "AnalyticsDonutMinor" },
    { icon: AnalyticsFilledMinor, name: "AnalyticsFilledMinor" },
    { icon: AnalyticsFunnelMinor, name: "AnalyticsFunnelMinor" },
    { icon: AnalyticsLineMinor, name: "AnalyticsLineMinor" },
    { icon: AnalyticsMajor, name: "AnalyticsMajor" },
    { icon: AnalyticsMinor, name: "AnalyticsMinor" },
    { icon: AnalyticsTableMinor, name: "AnalyticsTableMinor" },
    { icon: AnyClickModelMinor, name: "AnyClickModelMinor" },
    { icon: AppExtensionMinor, name: "AppExtensionMinor" },
    { icon: AppsFilledMajor, name: "AppsFilledMajor" },
    { icon: AppsMajor, name: "AppsMajor" },
    { icon: AppsMinor, name: "AppsMinor" },
    { icon: ArchiveMajor, name: "ArchiveMajor" },
    { icon: ArchiveMinor, name: "ArchiveMinor" },
    { icon: ArrowDownMinor, name: "ArrowDownMinor" },
    { icon: ArrowLeftMinor, name: "ArrowLeftMinor" },
    { icon: ArrowRightMinor, name: "ArrowRightMinor" },
    { icon: ArrowUpMinor, name: "ArrowUpMinor" },
    { icon: AttachmentFilledMajor, name: "AttachmentFilledMajor" },
    { icon: AttachmentMajor, name: "AttachmentMajor" },
    { icon: AutomationFilledMajor, name: "AutomationFilledMajor" },
    { icon: AutomationMajor, name: "AutomationMajor" },
    { icon: BackspaceMajor, name: "BackspaceMajor" },
    { icon: BalanceFilledMajor, name: "BalanceFilledMajor" },
    { icon: BalanceMajor, name: "BalanceMajor" },
    { icon: BankFilledMajor, name: "BankFilledMajor" },
    { icon: BankMajor, name: "BankMajor" },
    { icon: BarcodeMajor, name: "BarcodeMajor" },
    { icon: BehaviorFilledMajor, name: "BehaviorFilledMajor" },
    { icon: BehaviorMajor, name: "BehaviorMajor" },
    { icon: BehaviorMinor, name: "BehaviorMinor" },
    { icon: BillingStatementDollarFilledMajor, name: "BillingStatementDollarFilledMajor" },
    { icon: BillingStatementDollarMajor, name: "BillingStatementDollarMajor" },
    { icon: BillingStatementEuroFilledMajor, name: "BillingStatementEuroFilledMajor" },
    { icon: BillingStatementEuroMajor, name: "BillingStatementEuroMajor" },
    { icon: BillingStatementPoundFilledMajor, name: "BillingStatementPoundFilledMajor" },
    { icon: BillingStatementPoundMajor, name: "BillingStatementPoundMajor" },
    { icon: BillingStatementRupeeFilledMajor, name: "BillingStatementRupeeFilledMajor" },
    { icon: BillingStatementRupeeMajor, name: "BillingStatementRupeeMajor" },
    { icon: BillingStatementYenFilledMajor, name: "BillingStatementYenFilledMajor" },
    { icon: BillingStatementYenMajor, name: "BillingStatementYenMajor" },
    { icon: BlockMinor, name: "BlockMinor" },
    { icon: BlockquoteMajor, name: "BlockquoteMajor" },
    { icon: BlogMajor, name: "BlogMajor" },
    { icon: BoldMajor, name: "BoldMajor" },
    { icon: BoldMinor, name: "BoldMinor" },
    { icon: BugMajor, name: "BugMajor" },
    { icon: ButtonCornerPillMajor, name: "ButtonCornerPillMajor" },
    { icon: ButtonCornerRoundedMajor, name: "ButtonCornerRoundedMajor" },
    { icon: ButtonCornerSquareMajor, name: "ButtonCornerSquareMajor" },
    { icon: ButtonMinor, name: "ButtonMinor" },
    { icon: BuyButtonButtonLayoutMajor, name: "BuyButtonButtonLayoutMajor" },
    { icon: BuyButtonHorizontalLayoutMajor, name: "BuyButtonHorizontalLayoutMajor" },
    { icon: BuyButtonMajor, name: "BuyButtonMajor" },
    { icon: BuyButtonVerticalLayoutMajor, name: "BuyButtonVerticalLayoutMajor" },
    { icon: CalendarMajor, name: "CalendarMajor" },
    { icon: CalendarMinor, name: "CalendarMinor" },
    { icon: CalendarTickMajor, name: "CalendarTickMajor" },
    { icon: CalendarTimeMinor, name: "CalendarTimeMinor" },
    { icon: CameraMajor, name: "CameraMajor" },
    { icon: CancelMajor, name: "CancelMajor" },
    { icon: CancelMinor, name: "CancelMinor" },
    { icon: CancelSmallMinor, name: "CancelSmallMinor" },
    { icon: CapitalFilledMajor, name: "CapitalFilledMajor" },
    { icon: CapitalMajor, name: "CapitalMajor" },
    { icon: CapturePaymentMinor, name: "CapturePaymentMinor" },
    { icon: CardReaderChipMajor, name: "CardReaderChipMajor" },
    { icon: CardReaderMajor, name: "CardReaderMajor" },
    { icon: CardReaderTapMajor, name: "CardReaderTapMajor" },
    { icon: CaretDownMinor, name: "CaretDownMinor" },
    { icon: CaretUpMinor, name: "CaretUpMinor" },
    { icon: CartDownFilledMajor, name: "CartDownFilledMajor" },
    { icon: CartDownMajor, name: "CartDownMajor" },
    { icon: CartFilledMajor, name: "CartFilledMajor" },
    { icon: CartMajor, name: "CartMajor" },
    { icon: CartUpMajor, name: "CartUpMajor" },
    { icon: CashDollarFilledMajor, name: "CashDollarFilledMajor" },
    { icon: CashDollarMajor, name: "CashDollarMajor" },
    { icon: CashDollarMinor, name: "CashDollarMinor" },
    { icon: CashEuroMajor, name: "CashEuroMajor" },
    { icon: CashPoundMajor, name: "CashPoundMajor" },
    { icon: CashRupeeMajor, name: "CashRupeeMajor" },
    { icon: CashYenMajor, name: "CashYenMajor" },
    { icon: CategoriesMajor, name: "CategoriesMajor" },
    { icon: ChannelsMajor, name: "ChannelsMajor" },
    { icon: ChatMajor, name: "ChatMajor" },
    { icon: ChecklistAlternateMajor, name: "ChecklistAlternateMajor" },
    { icon: ChecklistMajor, name: "ChecklistMajor" },
    { icon: CheckoutMajor, name: "CheckoutMajor" },
    { icon: ChevronDownMinor, name: "ChevronDownMinor" },
    { icon: ChevronLeftMinor, name: "ChevronLeftMinor" },
    { icon: ChevronRightMinor, name: "ChevronRightMinor" },
    { icon: ChevronUpMinor, name: "ChevronUpMinor" },
    { icon: CircleAlertMajor, name: "CircleAlertMajor" },
    { icon: CircleCancelMajor, name: "CircleCancelMajor" },
    { icon: CircleCancelMinor, name: "CircleCancelMinor" },
    { icon: CircleChevronDownMinor, name: "CircleChevronDownMinor" },
    { icon: CircleChevronLeftMinor, name: "CircleChevronLeftMinor" },
    { icon: CircleChevronRightMinor, name: "CircleChevronRightMinor" },
    { icon: CircleChevronUpMinor, name: "CircleChevronUpMinor" },
    { icon: CircleDisableMinor, name: "CircleDisableMinor" },
    { icon: CircleDisabledMajor, name: "CircleDisabledMajor" },
    { icon: CircleDotsMajor, name: "CircleDotsMajor" },
    { icon: CircleDownMajor, name: "CircleDownMajor" },
    { icon: CircleInformationMajor, name: "CircleInformationMajor" },
    { icon: CircleLeftMajor, name: "CircleLeftMajor" },
    { icon: CircleMinusMajor, name: "CircleMinusMajor" },
    { icon: CircleMinusMinor, name: "CircleMinusMinor" },
    { icon: CircleMinusOutlineMinor, name: "CircleMinusOutlineMinor" },
    { icon: CirclePlusMajor, name: "CirclePlusMajor" },
    { icon: CirclePlusMinor, name: "CirclePlusMinor" },
    { icon: CirclePlusOutlineMinor, name: "CirclePlusOutlineMinor" },
    { icon: CircleRightMajor, name: "CircleRightMajor" },
    { icon: CircleTickMajor, name: "CircleTickMajor" },
    { icon: CircleTickMinor, name: "CircleTickMinor" },
    { icon: CircleTickOutlineMinor, name: "CircleTickOutlineMinor" },
    { icon: CircleUpMajor, name: "CircleUpMajor" },
    { icon: ClipboardMinor, name: "ClipboardMinor" },
    { icon: ClockMajor, name: "ClockMajor" },
    { icon: ClockMinor, name: "ClockMinor" },
    { icon: CodeMajor, name: "CodeMajor" },
    { icon: CodeMinor, name: "CodeMinor" },
    { icon: CollectionReferenceMinor, name: "CollectionReferenceMinor" },
    { icon: CollectionsFilledMajor, name: "CollectionsFilledMajor" },
    { icon: CollectionsMajor, name: "CollectionsMajor" },
    { icon: ColorNoneMinor, name: "ColorNoneMinor" },
    { icon: ColorsMajor, name: "ColorsMajor" },
    { icon: Column1Major, name: "Column1Major" },
    { icon: ColumnWithTextMajor, name: "ColumnWithTextMajor" },
    { icon: Columns2Major, name: "Columns2Major" },
    { icon: Columns3Major, name: "Columns3Major" },
    { icon: Columns3Minor, name: "Columns3Minor" },
    { icon: ComposeMajor, name: "ComposeMajor" },
    { icon: ConfettiMajor, name: "ConfettiMajor" },
    { icon: ConnectMinor, name: "ConnectMinor" },
    { icon: ContentFilledMinor, name: "ContentFilledMinor" },
    { icon: ContentMinor, name: "ContentMinor" },
    { icon: ConversationMinor, name: "ConversationMinor" },
    { icon: CreditCardCancelMajor, name: "CreditCardCancelMajor" },
    { icon: CreditCardMajor, name: "CreditCardMajor" },
    { icon: CreditCardPercentMajor, name: "CreditCardPercentMajor" },
    { icon: CreditCardSecureMajor, name: "CreditCardSecureMajor" },
    { icon: CurrencyConvertMinor, name: "CurrencyConvertMinor" },
    { icon: CustomerMinusMajor, name: "CustomerMinusMajor" },
    { icon: CustomerPlusMajor, name: "CustomerPlusMajor" },
    { icon: CustomersFilledMinor, name: "CustomersFilledMinor" },
    { icon: CustomersMajor, name: "CustomersMajor" },
    { icon: CustomersMinor, name: "CustomersMinor" },
    { icon: DataDrivenModelMinor, name: "DataDrivenModelMinor" },
    { icon: DataVisualizationMajor, name: "DataVisualizationMajor" },
    { icon: DecimalMinor, name: "DecimalMinor" },
    { icon: DeleteMajor, name: "DeleteMajor" },
    { icon: DeleteMinor, name: "DeleteMinor" },
    { icon: DesktopMajor, name: "DesktopMajor" },
    { icon: DetailedPopUpMajor, name: "DetailedPopUpMajor" },
    { icon: DiamondAlertMajor, name: "DiamondAlertMajor" },
    { icon: DiamondAlertMinor, name: "DiamondAlertMinor" },
    { icon: DigitalMediaReceiverMajor, name: "DigitalMediaReceiverMajor" },
    { icon: DiscountAutomaticMajor, name: "DiscountAutomaticMajor" },
    { icon: DiscountCodeMajor, name: "DiscountCodeMajor" },
    { icon: DiscountsFilledMinor, name: "DiscountsFilledMinor" },
    { icon: DiscountsMajor, name: "DiscountsMajor" },
    { icon: DiscountsMinor, name: "DiscountsMinor" },
    { icon: DisputeMinor, name: "DisputeMinor" },
    { icon: DnsSettingsMajor, name: "DnsSettingsMajor" },
    { icon: DockFloatingMajor, name: "DockFloatingMajor" },
    { icon: DockSideMajor, name: "DockSideMajor" },
    { icon: DomainNewMajor, name: "DomainNewMajor" },
    { icon: DomainRedirectMinor, name: "DomainRedirectMinor" },
    { icon: DomainsFilledMajor, name: "DomainsFilledMajor" },
    { icon: DomainsMajor, name: "DomainsMajor" },
    { icon: DraftOrdersFilledMajor, name: "DraftOrdersFilledMajor" },
    { icon: DraftOrdersMajor, name: "DraftOrdersMajor" },
    { icon: DragDropMajor, name: "DragDropMajor" },
    { icon: DragHandleMinor, name: "DragHandleMinor" },
    { icon: DropdownMinor, name: "DropdownMinor" },
    { icon: DuplicateMinor, name: "DuplicateMinor" },
    { icon: DynamicSourceMajor, name: "DynamicSourceMajor" },
    { icon: DynamicSourceMinor, name: "DynamicSourceMinor" },
    { icon: EditMajor, name: "EditMajor" },
    { icon: EditMinor, name: "EditMinor" },
    { icon: EmailMajor, name: "EmailMajor" },
    { icon: EmailNewsletterMajor, name: "EmailNewsletterMajor" },
    { icon: EmbedMinor, name: "EmbedMinor" },
    { icon: EnableSelectionMinor, name: "EnableSelectionMinor" },
    { icon: EnterMajor, name: "EnterMajor" },
    { icon: EnvelopeMajor, name: "EnvelopeMajor" },
    { icon: ExchangeMajor, name: "ExchangeMajor" },
    { icon: ExistingInventoryMajor, name: "ExistingInventoryMajor" },
    { icon: ExitMajor, name: "ExitMajor" },
    { icon: ExploreImagesMajor, name: "ExploreImagesMajor" },
    { icon: ExportMinor, name: "ExportMinor" },
    { icon: ExtendMajor, name: "ExtendMajor" },
    { icon: ExtendMinor, name: "ExtendMinor" },
    { icon: ExternalMinor, name: "ExternalMinor" },
    { icon: ExternalSmallMinor, name: "ExternalSmallMinor" },
    { icon: EyeDropperMinor, name: "EyeDropperMinor" },
    { icon: FacebookMinor, name: "FacebookMinor" },
    { icon: FaviconMajor, name: "FaviconMajor" },
    { icon: FavoriteMajor, name: "FavoriteMajor" },
    { icon: FeaturedCollectionMajor, name: "FeaturedCollectionMajor" },
    { icon: FeaturedContentMajor, name: "FeaturedContentMajor" },
    { icon: FileFilledMinor, name: "FileFilledMinor" },
    { icon: FileMinor, name: "FileMinor" },
    { icon: FilterMajor, name: "FilterMajor" },
    { icon: FilterMinor, name: "FilterMinor" },
    { icon: FinancesMajor, name: "FinancesMajor" },
    { icon: FinancesMinor, name: "FinancesMinor" },
    { icon: FirstClickModelMinor, name: "FirstClickModelMinor" },
    { icon: FirstOrderMajor, name: "FirstOrderMajor" },
    { icon: FirstVisitMajor, name: "FirstVisitMajor" },
    { icon: FlagMajor, name: "FlagMajor" },
    { icon: FlipCameraMajor, name: "FlipCameraMajor" },
    { icon: FolderDownMajor, name: "FolderDownMajor" },
    { icon: FolderMajor, name: "FolderMajor" },
    { icon: FolderMinusMajor, name: "FolderMinusMajor" },
    { icon: FolderPlusMajor, name: "FolderPlusMajor" },
    { icon: FolderUpMajor, name: "FolderUpMajor" },
    { icon: FollowUpEmailMajor, name: "FollowUpEmailMajor" },
    { icon: FoodMajor, name: "FoodMajor" },
    { icon: FooterMajor, name: "FooterMajor" },
    { icon: FormsMajor, name: "FormsMajor" },
    { icon: FraudProtectMajor, name: "FraudProtectMajor" },
    { icon: FraudProtectMinor, name: "FraudProtectMinor" },
    { icon: FraudProtectPendingMajor, name: "FraudProtectPendingMajor" },
    { icon: FraudProtectPendingMinor, name: "FraudProtectPendingMinor" },
    { icon: FraudProtectUnprotectedMajor, name: "FraudProtectUnprotectedMajor" },
    { icon: FraudProtectUnprotectedMinor, name: "FraudProtectUnprotectedMinor" },
    { icon: FulfillmentFulfilledMajor, name: "FulfillmentFulfilledMajor" },
    { icon: FulfillmentOnHoldMajor, name: "FulfillmentOnHoldMajor" },
    { icon: GamesConsoleMajor, name: "GamesConsoleMajor" },
    { icon: GaugeMajor, name: "GaugeMajor" },
    { icon: GaugeMinor, name: "GaugeMinor" },
    { icon: GiftCardFilledMinor, name: "GiftCardFilledMinor" },
    { icon: GiftCardMajor, name: "GiftCardMajor" },
    { icon: GiftCardMinor, name: "GiftCardMinor" },
    { icon: GlobeMajor, name: "GlobeMajor" },
    { icon: GlobeMinor, name: "GlobeMinor" },
    { icon: GrammarMajor, name: "GrammarMajor" },
    { icon: HashtagMajor, name: "HashtagMajor" },
    { icon: HashtagMinor, name: "HashtagMinor" },
    { icon: HeaderMajor, name: "HeaderMajor" },
    { icon: HeartMajor, name: "HeartMajor" },
    { icon: HideKeyboardMajor, name: "HideKeyboardMajor" },
    { icon: HideMinor, name: "HideMinor" },
    { icon: HintMajor, name: "HintMajor" },
    { icon: HomeFilledMinor, name: "HomeFilledMinor" },
    { icon: HomeMajor, name: "HomeMajor" },
    { icon: HomeMinor, name: "HomeMinor" },
    { icon: HorizontalDotsMinor, name: "HorizontalDotsMinor" },
    { icon: IconsFilledMajor, name: "IconsFilledMajor" },
    { icon: IconsMajor, name: "IconsMajor" },
    { icon: IdentityCardFilledMajor, name: "IdentityCardFilledMajor" },
    { icon: IdentityCardMajor, name: "IdentityCardMajor" },
    { icon: IllustrationMajor, name: "IllustrationMajor" },
    { icon: ImageAltMajor, name: "ImageAltMajor" },
    { icon: ImageAltMinor, name: "ImageAltMinor" },
    { icon: ImageMajor, name: "ImageMajor" },
    { icon: ImageWithTextMajor, name: "ImageWithTextMajor" },
    { icon: ImageWithTextOverlayMajor, name: "ImageWithTextOverlayMajor" },
    { icon: ImagesMajor, name: "ImagesMajor" },
    { icon: ImportMinor, name: "ImportMinor" },
    { icon: ImportStoreMajor, name: "ImportStoreMajor" },
    { icon: InactiveLocationMajor, name: "InactiveLocationMajor" },
    { icon: InactiveLocationMinor, name: "InactiveLocationMinor" },
    { icon: IncomingMajor, name: "IncomingMajor" },
    { icon: IndentMajor, name: "IndentMajor" },
    { icon: IndentMinor, name: "IndentMinor" },
    { icon: InfoMinor, name: "InfoMinor" },
    { icon: InsertDynamicSourceMajor, name: "InsertDynamicSourceMajor" },
    { icon: InsertDynamicSourceMinor, name: "InsertDynamicSourceMinor" },
    { icon: InstagramMinor, name: "InstagramMinor" },
    { icon: InstallMinor, name: "InstallMinor" },
    { icon: InventoryFilledMajor, name: "InventoryFilledMajor" },
    { icon: InventoryMajor, name: "InventoryMajor" },
    { icon: InviteMinor, name: "InviteMinor" },
    { icon: IqMajor, name: "IqMajor" },
    { icon: ItalicMajor, name: "ItalicMajor" },
    { icon: ItalicMinor, name: "ItalicMinor" },
    { icon: JobsFilledMajor, name: "JobsFilledMajor" },
    { icon: JobsMajor, name: "JobsMajor" },
    { icon: KeyMajor, name: "KeyMajor" },
    { icon: KeyboardMajor, name: "KeyboardMajor" },
    { icon: KeyboardMinor, name: "KeyboardMinor" },
    { icon: LabelPrinterMajor, name: "LabelPrinterMajor" },
    { icon: LandingPageMajor, name: "LandingPageMajor" },
    { icon: LanguageFilledMinor, name: "LanguageFilledMinor" },
    { icon: LanguageMinor, name: "LanguageMinor" },
    { icon: LastClickModelMinor, name: "LastClickModelMinor" },
    { icon: LastNonDirectClickModelMinor, name: "LastNonDirectClickModelMinor" },
    { icon: LegalFilledMajor, name: "LegalFilledMajor" },
    { icon: LegalMajor, name: "LegalMajor" },
    { icon: LinearModelMinor, name: "LinearModelMinor" },
    { icon: LinkMinor, name: "LinkMinor" },
    { icon: ListFilledMajor, name: "ListFilledMajor" },
    { icon: ListMajor, name: "ListMajor" },
    { icon: ListMinor, name: "ListMinor" },
    { icon: LiveViewFilledMajor, name: "LiveViewFilledMajor" },
    { icon: LiveViewMajor, name: "LiveViewMajor" },
    { icon: LocationFilledMajor, name: "LocationFilledMajor" },
    { icon: LocationMajor, name: "LocationMajor" },
    { icon: LocationsMinor, name: "LocationsMinor" },
    { icon: LockFilledMajor, name: "LockFilledMajor" },
    { icon: LockMajor, name: "LockMajor" },
    { icon: LockMinor, name: "LockMinor" },
    { icon: LogOutMinor, name: "LogOutMinor" },
    { icon: LogoBlockMajor, name: "LogoBlockMajor" },
    { icon: MagicMajor, name: "MagicMajor" },
    { icon: MagicMinor, name: "MagicMinor" },
    { icon: ManagedStoreMajor, name: "ManagedStoreMajor" },
    { icon: MarkFulfilledMinor, name: "MarkFulfilledMinor" },
    { icon: MarkPaidMinor, name: "MarkPaidMinor" },
    { icon: MarketingFilledMinor, name: "MarketingFilledMinor" },
    { icon: MarketingMajor, name: "MarketingMajor" },
    { icon: MarketingMinor, name: "MarketingMinor" },
    { icon: MarketsFilledMajor, name: "MarketsFilledMajor" },
    { icon: MarketsMajor, name: "MarketsMajor" },
    { icon: MaximizeMajor, name: "MaximizeMajor" },
    { icon: MaximizeMinor, name: "MaximizeMinor" },
    { icon: MeasurementMinor, name: "MeasurementMinor" },
    { icon: MentionMajor, name: "MentionMajor" },
    { icon: MergeMinor, name: "MergeMinor" },
    { icon: MetafieldsFilledMinor, name: "MetafieldsFilledMinor" },
    { icon: MetafieldsMajor, name: "MetafieldsMajor" },
    { icon: MetafieldsMinor, name: "MetafieldsMinor" },
    { icon: MetaobjectMinor, name: "MetaobjectMinor" },
    { icon: MetaobjectReferenceMinor, name: "MetaobjectReferenceMinor" },
    { icon: MicrophoneMajor, name: "MicrophoneMajor" },
    { icon: MinimizeMajor, name: "MinimizeMajor" },
    { icon: MinimizeMinor, name: "MinimizeMinor" },
    { icon: MinusMajor, name: "MinusMajor" },
    { icon: MinusMinor, name: "MinusMinor" },
    { icon: MobileAcceptMajor, name: "MobileAcceptMajor" },
    { icon: MobileBackArrowMajor, name: "MobileBackArrowMajor" },
    { icon: MobileCancelMajor, name: "MobileCancelMajor" },
    { icon: MobileChevronMajor, name: "MobileChevronMajor" },
    { icon: MobileHamburgerMajor, name: "MobileHamburgerMajor" },
    { icon: MobileHorizontalDotsMajor, name: "MobileHorizontalDotsMajor" },
    { icon: MobileMajor, name: "MobileMajor" },
    { icon: MobilePlusMajor, name: "MobilePlusMajor" },
    { icon: MobileVerticalDotsMajor, name: "MobileVerticalDotsMajor" },
    { icon: MonerisMajor, name: "MonerisMajor" },
    { icon: MoneyFilledMinor, name: "MoneyFilledMinor" },
    { icon: MoneyMinor, name: "MoneyMinor" },
    { icon: NatureMajor, name: "NatureMajor" },
    { icon: NavigationMajor, name: "NavigationMajor" },
    { icon: NoteMajor, name: "NoteMajor" },
    { icon: NoteMinor, name: "NoteMinor" },
    { icon: NotificationFilledMajor, name: "NotificationFilledMajor" },
    { icon: NotificationMajor, name: "NotificationMajor" },
    { icon: OnlineStoreMajor, name: "OnlineStoreMajor" },
    { icon: OnlineStoreMinor, name: "OnlineStoreMinor" },
    { icon: OrderStatusMinor, name: "OrderStatusMinor" },
    { icon: OrderedListMajor, name: "OrderedListMajor" },
    { icon: OrderedListMinor, name: "OrderedListMinor" },
    { icon: OrdersFilledMinor, name: "OrdersFilledMinor" },
    { icon: OrdersMajor, name: "OrdersMajor" },
    { icon: OrdersMinor, name: "OrdersMinor" },
    { icon: OrganizationMajor, name: "OrganizationMajor" },
    { icon: OutdentMajor, name: "OutdentMajor" },
    { icon: OutdentMinor, name: "OutdentMinor" },
    { icon: OutgoingMajor, name: "OutgoingMajor" },
    { icon: PackageFilledMajor, name: "PackageFilledMajor" },
    { icon: PackageMajor, name: "PackageMajor" },
    { icon: PageDownMajor, name: "PageDownMajor" },
    { icon: PageMajor, name: "PageMajor" },
    { icon: PageMinusMajor, name: "PageMinusMajor" },
    { icon: PagePlusMajor, name: "PagePlusMajor" },
    { icon: PageReferenceMinor, name: "PageReferenceMinor" },
    { icon: PageUpMajor, name: "PageUpMajor" },
    { icon: PaginationEndMinor, name: "PaginationEndMinor" },
    { icon: PaginationStartMinor, name: "PaginationStartMinor" },
    { icon: PaintBrushMajor, name: "PaintBrushMajor" },
    { icon: PaperCheckMajor, name: "PaperCheckMajor" },
    { icon: PaperCheckMinor, name: "PaperCheckMinor" },
    { icon: PasskeyFilledMinor, name: "PasskeyFilledMinor" },
    { icon: PasskeyMajor, name: "PasskeyMajor" },
    { icon: PasskeyMinor, name: "PasskeyMinor" },
    { icon: PauseCircleMajor, name: "PauseCircleMajor" },
    { icon: PauseMajor, name: "PauseMajor" },
    { icon: PauseMinor, name: "PauseMinor" },
    { icon: PaymentsFilledMajor, name: "PaymentsFilledMajor" },
    { icon: PaymentsMajor, name: "PaymentsMajor" },
    { icon: PayoutsBlockedMinor, name: "PayoutsBlockedMinor" },
    { icon: PersonalizedTextMajor, name: "PersonalizedTextMajor" },
    { icon: PhoneInMajor, name: "PhoneInMajor" },
    { icon: PhoneMajor, name: "PhoneMajor" },
    { icon: PhoneOutMajor, name: "PhoneOutMajor" },
    { icon: PinMajor, name: "PinMajor" },
    { icon: PinMinor, name: "PinMinor" },
    { icon: PinUnfilledMajor, name: "PinUnfilledMajor" },
    { icon: PinUnfilledMinor, name: "PinUnfilledMinor" },
    { icon: PintrestMinor, name: "PintrestMinor" },
    { icon: PlanFilledMinor, name: "PlanFilledMinor" },
    { icon: PlanMajor, name: "PlanMajor" },
    { icon: PlanMinor, name: "PlanMinor" },
    { icon: PlayCircleMajor, name: "PlayCircleMajor" },
    { icon: PlayMajor, name: "PlayMajor" },
    { icon: PlayMinor, name: "PlayMinor" },
    { icon: PlusMinor, name: "PlusMinor" },
    { icon: PointOfSaleMajor, name: "PointOfSaleMajor" },
    { icon: PopularMajor, name: "PopularMajor" },
    { icon: PositionBasedModelMinor, name: "PositionBasedModelMinor" },
    { icon: PriceLookupMinor, name: "PriceLookupMinor" },
    { icon: PrintMajor, name: "PrintMajor" },
    { icon: PrintMinor, name: "PrintMinor" },
    { icon: ProductCostMajor, name: "ProductCostMajor" },
    { icon: ProductReferenceMinor, name: "ProductReferenceMinor" },
    { icon: ProductReturnsMinor, name: "ProductReturnsMinor" },
    { icon: ProductsFilledMinor, name: "ProductsFilledMinor" },
    { icon: ProductsMajor, name: "ProductsMajor" },
    { icon: ProductsMinor, name: "ProductsMinor" },
    { icon: ProfileMajor, name: "ProfileMajor" },
    { icon: ProfileMinor, name: "ProfileMinor" },
    { icon: PromoteFilledMinor, name: "PromoteFilledMinor" },
    { icon: PromoteMinor, name: "PromoteMinor" },
    { icon: QuestionMarkInverseMajor, name: "QuestionMarkInverseMajor" },
    { icon: QuestionMarkInverseMinor, name: "QuestionMarkInverseMinor" },
    { icon: QuestionMarkMajor, name: "QuestionMarkMajor" },
    { icon: QuestionMarkMinor, name: "QuestionMarkMinor" },
    { icon: QuickSaleMajor, name: "QuickSaleMajor" },
    { icon: ReadTimeMinor, name: "ReadTimeMinor" },
    { icon: ReceiptMajor, name: "ReceiptMajor" },
    { icon: RecentSearchesMajor, name: "RecentSearchesMajor" },
    { icon: RedoMajor, name: "RedoMajor" },
    { icon: ReferralCodeMajor, name: "ReferralCodeMajor" },
    { icon: ReferralMajor, name: "ReferralMajor" },
    { icon: RefreshMajor, name: "RefreshMajor" },
    { icon: RefreshMinor, name: "RefreshMinor" },
    { icon: RefundMajor, name: "RefundMajor" },
    { icon: RefundMinor, name: "RefundMinor" },
    { icon: RemoveProductMajor, name: "RemoveProductMajor" },
    { icon: RepeatOrderMajor, name: "RepeatOrderMajor" },
    { icon: ReplaceMajor, name: "ReplaceMajor" },
    { icon: ReplayMinor, name: "ReplayMinor" },
    { icon: ReportFilledMinor, name: "ReportFilledMinor" },
    { icon: ReportMinor, name: "ReportMinor" },
    { icon: ReportsMajor, name: "ReportsMajor" },
    { icon: ResetMinor, name: "ResetMinor" },
    { icon: ResourcesMajor, name: "ResourcesMajor" },
    { icon: ReturnMinor, name: "ReturnMinor" },
    { icon: ReturnsMajor, name: "ReturnsMajor" },
    { icon: RichTextMinor, name: "RichTextMinor" },
    { icon: RiskMajor, name: "RiskMajor" },
    { icon: RiskMinor, name: "RiskMinor" },
    { icon: Rows2Major, name: "Rows2Major" },
    { icon: SandboxMajor, name: "SandboxMajor" },
    { icon: SaveMinor, name: "SaveMinor" },
    { icon: SearchMajor, name: "SearchMajor" },
    { icon: SearchMinor, name: "SearchMinor" },
    { icon: SectionMajor, name: "SectionMajor" },
    { icon: SecureMajor, name: "SecureMajor" },
    { icon: SelectMinor, name: "SelectMinor" },
    { icon: SendMajor, name: "SendMajor" },
    { icon: SettingsFilledMinor, name: "SettingsFilledMinor" },
    { icon: SettingsMajor, name: "SettingsMajor" },
    { icon: SettingsMinor, name: "SettingsMinor" },
    { icon: ShareIosMinor, name: "ShareIosMinor" },
    { icon: ShareMinor, name: "ShareMinor" },
    { icon: ShipmentFilledMajor, name: "ShipmentFilledMajor" },
    { icon: ShipmentMajor, name: "ShipmentMajor" },
    { icon: ShopcodesMajor, name: "ShopcodesMajor" },
    { icon: SidebarLeftMajor, name: "SidebarLeftMajor" },
    { icon: SidebarRightMajor, name: "SidebarRightMajor" },
    { icon: SidekickMajor, name: "SidekickMajor" },
    { icon: SimplifyMajor, name: "SimplifyMajor" },
    { icon: SimplifyMinor, name: "SimplifyMinor" },
    { icon: SlideshowMajor, name: "SlideshowMajor" },
    { icon: SmileyHappyMajor, name: "SmileyHappyMajor" },
    { icon: SmileyJoyMajor, name: "SmileyJoyMajor" },
    { icon: SmileyNeutralMajor, name: "SmileyNeutralMajor" },
    { icon: SmileySadMajor, name: "SmileySadMajor" },
    { icon: SnapchatMinor, name: "SnapchatMinor" },
    { icon: SocialAdMajor, name: "SocialAdMajor" },
    { icon: SocialPostMajor, name: "SocialPostMajor" },
    { icon: SoftPackMajor, name: "SoftPackMajor" },
    { icon: SortAscendingMajor, name: "SortAscendingMajor" },
    { icon: SortDescendingMajor, name: "SortDescendingMajor" },
    { icon: SortMinor, name: "SortMinor" },
    { icon: SoundMajor, name: "SoundMajor" },
    { icon: StarFilledMinor, name: "StarFilledMinor" },
    { icon: StarOutlineMinor, name: "StarOutlineMinor" },
    { icon: StatusActiveMajor, name: "StatusActiveMajor" },
    { icon: StopMajor, name: "StopMajor" },
    { icon: StoreDetailsFilledMinor, name: "StoreDetailsFilledMinor" },
    { icon: StoreDetailsMinor, name: "StoreDetailsMinor" },
    { icon: StoreFilledMinor, name: "StoreFilledMinor" },
    { icon: StoreMajor, name: "StoreMajor" },
    { icon: StoreMinor, name: "StoreMinor" },
    { icon: StoreStatusMajor, name: "StoreStatusMajor" },
    { icon: TabletMajor, name: "TabletMajor" },
    { icon: TapChipMajor, name: "TapChipMajor" },
    { icon: TaxFilledMajor, name: "TaxFilledMajor" },
    { icon: TaxMajor, name: "TaxMajor" },
    { icon: TeamMajor, name: "TeamMajor" },
    { icon: TemplateMajor, name: "TemplateMajor" },
    { icon: TemplateMinor, name: "TemplateMinor" },
    { icon: TextAlignmentCenterMajor, name: "TextAlignmentCenterMajor" },
    { icon: TextAlignmentLeftMajor, name: "TextAlignmentLeftMajor" },
    { icon: TextAlignmentRightMajor, name: "TextAlignmentRightMajor" },
    { icon: TextBlockMajor, name: "TextBlockMajor" },
    { icon: TextColorMajor, name: "TextColorMajor" },
    { icon: TextColorMinor, name: "TextColorMinor" },
    { icon: TextMajor, name: "TextMajor" },
    { icon: ThemeEditMajor, name: "ThemeEditMajor" },
    { icon: ThemeStoreMajor, name: "ThemeStoreMajor" },
    { icon: ThemesMajor, name: "ThemesMajor" },
    { icon: ThumbsDownMajor, name: "ThumbsDownMajor" },
    { icon: ThumbsDownMinor, name: "ThumbsDownMinor" },
    { icon: ThumbsUpMajor, name: "ThumbsUpMajor" },
    { icon: ThumbsUpMinor, name: "ThumbsUpMinor" },
    { icon: TickMinor, name: "TickMinor" },
    { icon: TickSmallMinor, name: "TickSmallMinor" },
    { icon: TiktokMinor, name: "TiktokMinor" },
    { icon: TimeDecayModelMinor, name: "TimeDecayModelMinor" },
    { icon: TimelineAttachmentMajor, name: "TimelineAttachmentMajor" },
    { icon: TipsMajor, name: "TipsMajor" },
    { icon: TitleMinor, name: "TitleMinor" },
    { icon: ToggleMinor, name: "ToggleMinor" },
    { icon: ToolsMajor, name: "ToolsMajor" },
    { icon: TransactionFeeDollarMajor, name: "TransactionFeeDollarMajor" },
    { icon: TransactionFeeEuroMajor, name: "TransactionFeeEuroMajor" },
    { icon: TransactionFeePoundMajor, name: "TransactionFeePoundMajor" },
    { icon: TransactionFeeRupeeMajor, name: "TransactionFeeRupeeMajor" },
    { icon: TransactionFeeYenMajor, name: "TransactionFeeYenMajor" },
    { icon: TransactionMajor, name: "TransactionMajor" },
    { icon: TransferFilledMajor, name: "TransferFilledMajor" },
    { icon: TransferInMajor, name: "TransferInMajor" },
    { icon: TransferMajor, name: "TransferMajor" },
    { icon: TransferOutMajor, name: "TransferOutMajor" },
    { icon: TransferWithinShopifyMajor, name: "TransferWithinShopifyMajor" },
    { icon: TranslateMajor, name: "TranslateMajor" },
    { icon: TransportMajor, name: "TransportMajor" },
    { icon: TroubleshootMajor, name: "TroubleshootMajor" },
    { icon: TumblrMinor, name: "TumblrMinor" },
    { icon: TwitchMinor, name: "TwitchMinor" },
    { icon: TwitterMinor, name: "TwitterMinor" },
    { icon: TypeMajor, name: "TypeMajor" },
    { icon: TypeMinor, name: "TypeMinor" },
    { icon: UnderlineMajor, name: "UnderlineMajor" },
    { icon: UnderlineMinor, name: "UnderlineMinor" },
    { icon: UndoMajor, name: "UndoMajor" },
    { icon: UnfulfilledMajor, name: "UnfulfilledMajor" },
    { icon: UnknownDeviceMajor, name: "UnknownDeviceMajor" },
    { icon: UpdateInventoryMajor, name: "UpdateInventoryMajor" },
    { icon: UploadMajor, name: "UploadMajor" },
    { icon: VariantMajor, name: "VariantMajor" },
    { icon: ViewMajor, name: "ViewMajor" },
    { icon: ViewMinor, name: "ViewMinor" },
    { icon: ViewportNarrowMajor, name: "ViewportNarrowMajor" },
    { icon: ViewportShortMajor, name: "ViewportShortMajor" },
    { icon: ViewportTallMajor, name: "ViewportTallMajor" },
    { icon: ViewportWideMajor, name: "ViewportWideMajor" },
    { icon: VimeoMinor, name: "VimeoMinor" },
    { icon: VocabularyMajor, name: "VocabularyMajor" },
    { icon: VolumeMinor, name: "VolumeMinor" },
    { icon: WandMajor, name: "WandMajor" },
    { icon: WandMinor, name: "WandMinor" },
    { icon: WearableMajor, name: "WearableMajor" },
    { icon: WeightMinor, name: "WeightMinor" },
    { icon: WholesaleMajor, name: "WholesaleMajor" },
    { icon: WifiMajor, name: "WifiMajor" },
    { icon: YoutubeMinor, name: "YoutubeMinor" },
  ];
  return (
    <div>
      <InlineGrid gap="400" columns={5}>
        {icons.map(({ icon, name }, index) => (
          <InlineStack key={index} gap="200">
            <InlineStack>
              <Icon source={icon} tone="base" />
            </InlineStack>
            <Text as="p">{name}</Text>
          </InlineStack>
        ))}
      </InlineGrid>
    </div>
  );
}
